=== JCR21598/Twin-Cities-webapp/XML/Cities_Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <xs:element name="Cities">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="City"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="City">
    <xs:complexType mixed="true">
      <xs:choice maxOccurs="unbounded" minOccurs="0">
        <xs:element ref="Country"/>
        <xs:element ref="Geo_location_lat"/>
        <xs:element ref="Geo_location_long"/>
        <xs:element ref="Name"/>
        <xs:element ref="Postcode"/>
        <xs:element ref="Currency"/>
        <xs:element ref="Photos"/>
        <xs:element ref="Places_of_interest"/>
        <xs:element ref="Population_density"/>
        <xs:element ref="Population_size"/>
        <xs:element ref="Time_zone"/>
        <xs:element ref="WOEID"/>
      </xs:choice>
      <xs:attribute name="City_ID" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Currency" type="xs:string"/>
  <xs:element name="Photos">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Photo"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Photo">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Name"/>
        <xs:element ref="Place_of_interest"/>
        <xs:element ref="Image_filepath"/>
      </xs:sequence>
      <xs:attribute name="Photo_ID" use="required" type="xs:integer"/>
      <xs:attribute name="Place_of_interest_City_City_ID" use="required" type="xs:integer"/>
      <xs:attribute name="Place_of_interest_Place_of_interest_ID" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Image_filepath" type="xs:string"/>
  <xs:element name="Places_of_interest">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Place_of_interest"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Population_density" type="xs:integer"/>
  <xs:element name="Population_size" type="xs:integer"/>
  <xs:element name="Time_zone" type="xs:string"/>
  <xs:element name="WOEID" type="xs:integer"/>
  <xs:element name="Name" type="xs:string"/>
  <xs:element name="Place_of_interest">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="City"/>
        <xs:element ref="Country"/>
        <xs:element ref="Geo_location_lat"/>
        <xs:element ref="Geo_location_long"/>
        <xs:element ref="Name"/>
        <xs:element ref="Postcode"/>
        <xs:element ref="Capacity"/>
        <xs:element ref="City_WOEID"/>
        <xs:element ref="Type"/>
        <xs:element ref="Year_of_construction"/>
      </xs:choice>
      <xs:attribute name="City_City_ID" type="xs:integer"/>
      <xs:attribute name="Place_of_interest_ID" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Capacity" type="xs:decimal" nillable="true"/>
  <xs:element name="City_WOEID" type="xs:integer"/>
  <xs:element name="Type" type="xs:NCName"/>
  <xs:element name="Year_of_construction" type="xs:decimal" nillable="true"/>
  <xs:element name="Geo_location_long" type="xs:decimal"/>
  <xs:element name="Country" type="xs:NCName"/>
  <xs:element name="Geo_location_lat" type="xs:decimal"/>
  <xs:element name="Postcode" type="xs:string"/>
</xs:schema>

=== JCR21598/Twin-Cities-webapp/XML/Cities.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Joseph Thomas-Williams
ID: 16024424
XML doc for twin cities data
Cities: Exeter, England and Rennes, France
-->
<Cities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Cities_Schema.xsd">
    
    <City City_ID='1'>
        <Name>Exeter</Name>
        <Country>England</Country>
        <Geo_location_long>-3.5339</Geo_location_long>
        <Geo_location_lat>50.7184</Geo_location_lat>
        <WOEID>19792</WOEID>
        <Postcode>EX</Postcode>
        <Time_zone>GMT/BST</Time_zone>
        <Population_size>128900</Population_size>
        <Population_density>2700</Population_density>
        <Currency>Pound Sterling</Currency>
        
        <Places_of_interest>
            
            <Place_of_interest Place_of_interest_ID='1' City_City_ID='1'>
                <Name>Exeter Cathedral</Name>
                <Type>Cathedral</Type>
                <City>Exeter</City>
                <Country>England</Country>
                <Geo_location_long>-3.5299</Geo_location_long>
                <Geo_location_lat>50.7225</Geo_location_lat>
                <City_WOEID>19792</City_WOEID>
                <Postcode>EX1 1HS</Postcode>
                <Capacity>1000</Capacity>
                <Year_of_construction>1400</Year_of_construction>
            </Place_of_interest>
            
            <Place_of_interest Place_of_interest_ID='2' City_City_ID='1'>
                <Name>Bury Meadow Park</Name>
                <Type>Park</Type>
                <City>Exeter</City>
                <Country>England</Country>
                <Geo_location_long>-3.5360</Geo_location_long>
                <Geo_location_lat>50.7284</Geo_location_lat>
                <City_WOEID>19792</City_WOEID>
                <Postcode>EX4 4HH</Postcode>
                <Capacity xsi:nil='true'></Capacity>
                <Year_of_construction>1850</Year_of_construction>
            </Place_of_interest>
            
            <Place_of_interest Place_of_interest_ID='3' City_City_ID='1'>
                <Name>Harry's Restaurant</Name>
                <Type>Restaurant</Type>
                <City>Exeter</City>
                <Country>England</Country>
                <Geo_location_long>-3.5264</Geo_location_long>
                <Geo_location_lat>50.7281</Geo_location_lat>
                <City_WOEID>19792</City_WOEID>
                <Postcode>EX4 6AP</Postcode>
                <Capacity xsi:nil='true'></Capacity>
                <Year_of_construction>1993</Year_of_construction>
            </Place_of_interest>
            
            <Place_of_interest Place_of_interest_ID='4' City_City_ID='1'>
                <Name>The Hole In The Wall</Name>
                <Type>Bar</Type>
                <City>Exeter</City>
                <Country>England</Country>
                <Geo_location_long>-3.5291</Geo_location_long>
                <Geo_location_lat>50.7255</Geo_location_lat>
                <City_WOEID>19792</City_WOEID>
                <Postcode>EX4 3PX</Postcode>
                <Capacity xsi:nil='true'></Capacity>
                <Year_of_construction>1964</Year_of_construction>
            </Place_of_interest>
            
            <Place_of_interest Place_of_interest_ID='5' City_City_ID='1'>
                <Name>Tea On The Green</Name>
                <Type>Restaurant</Type>
                <City>Exeter</City>
                <Country>England</Country>
                <Geo_location_long>-3.5299</Geo_location_long>
                <Geo_location_lat>50.7233</Geo_location_lat>
                <City_WOEID>19792</City_WOEID>
                <Postcode>EX1 1EZ</Postcode>
                <Capacity xsi:nil='true'></Capacity>
                <Year_of_construction>2009</Year_of_construction>
            </Place_of_interest>
            
            <Place_of_interest Place_of_interest_ID='6' City_City_ID='1'>
                <Name>Royal Albert Memorial Museum</Name>
                <Type>Museum</Type>
                <City>Exeter</City>
                <Country>England</Country>
                <Geo_location_long>-3.5322</Geo_location_long>
                <Geo_location_lat>50.7250</Geo_location_lat>
                <City_WOEID>19792</City_WOEID>
                <Postcode>EX4 3RX</Postcode>
                <Capacity xsi:nil='true'></Capacity>
                <Year_of_construction>1868</Year_of_construction>
            </Place_of_interest>
            
        </Places_of_interest>
        
        <Photos>
            
            <Photo Photo_ID='1' Place_of_interest_Place_of_interest_ID='1' Place_of_interest_City_City_ID='1'>
                <Name>Exeter Cathedral</Name>
                <Place_of_interest>Exeter Cathedral</Place_of_interest>
                <Image_filepath>photos/1.jpg</Image_filepath>
            </Photo> 
            
            <Photo Photo_ID='2' Place_of_interest_Place_of_interest_ID='2' Place_of_interest_City_City_ID='1'>
                <Name>Bury Meadow Park</Name>
                <Place_of_interest>Bury Meadow Park</Place_of_interest>
                <Image_filepath>photos/2.jpg</Image_filepath>
            </Photo>
            
            <Photo Photo_ID='3' Place_of_interest_Place_of_interest_ID='3' Place_of_interest_City_City_ID='1'>
                <Name>Harry's Restaurant</Name>
                <Place_of_interest>Harry's Restaurant</Place_of_interest>
                <Image_filepath>photos/3.jpg</Image_filepath>
            </Photo>
            
            <Photo Photo_ID='4' Place_of_interest_Place_of_interest_ID='4' Place_of_interest_City_City_ID='1'>
                <Name>The Hole In The Wall</Name>
                <Place_of_interest>The Hole In The Wall</Place_of_interest>
                <Image_filepath>photos/4.jpg</Image_filepath>
            </Photo>
            
            <Photo Photo_ID='5' Place_of_interest_Place_of_interest_ID='5' Place_of_interest_City_City_ID='1'>
                <Name>Tea On The Green</Name>
                <Place_of_interest>Tea On The Green</Place_of_interest>
                <Image_filepath>photos/5.jpg</Image_filepath>
            </Photo>
            
            <Photo Photo_ID='6' Place_of_interest_Place_of_interest_ID='6' Place_of_interest_City_City_ID='1'>
                <Name>Royal Albert Memorial Museum</Name>
                <Place_of_interest>Royal Albert Memorial Museum</Place_of_interest>
                <Image_filepath>photos/6.jpg</Image_filepath>
            </Photo>
            
        </Photos>
        
    </City>
    
    <City City_ID='2'>
        <Name>Rennes</Name>
        <Country>France</Country>
        <Geo_location_long>-1.6778</Geo_location_long>
        <Geo_location_lat>48.1173</Geo_location_lat>
        <WOEID>619163</WOEID>
        <Postcode>35000/35200/35700</Postcode>
        <Time_zone>CET/CEST</Time_zone>
        <Population_size>215366</Population_size>
        <Population_density>4300</Population_density>
        <Currency>Euro</Currency>
        
        <Places_of_interest>
            
            <Place_of_interest Place_of_interest_ID='7' City_City_ID='2'>
                <Name>Rennes Cathedral</Name>
                <Type>Cathedral</Type>
                <City>Rennes</City>
                <Country>France</Country>
                <Geo_location_long>-1.6839</Geo_location_long>
                <Geo_location_lat>48.1116</Geo_location_lat>
                <City_WOEID>619163</City_WOEID>
                <Postcode>35000</Postcode>
                <Capacity xsi:nil='true'></Capacity>
                <Year_of_construction>1845</Year_of_construction>
            </Place_of_interest>
            
            <Place_of_interest Place_of_interest_ID='8' City_City_ID='2'>
                <Name>Parc du Thabor</Name>
                <Type>Park</Type>
                <City>Rennes</City>
                <Country>France</Country>
                <Geo_location_long>-1.6695</Geo_location_long>
                <Geo_location_lat>48.1144</Geo_location_lat>
                <City_WOEID>619163</City_WOEID>
                <Postcode>35000</Postcode>
                <Capacity xsi:nil='true'></Capacity>
                <Year_of_construction xsi:nil='true'></Year_of_construction>
            </Place_of_interest>
            
            <Place_of_interest Place_of_interest_ID='9' City_City_ID='2'>
                <Name>Museum of Fine Arts of Rennes</Name>
                <Type>Museum</Type>
                <City>Rennes</City>
                <Country>France</Country>
                <Geo_location_long>-1.6750</Geo_location_long>
                <Geo_location_lat>48.1096</Geo_location_lat>
                <City_WOEID>619163</City_WOEID>
                <Postcode>35000</Postcode>
                <Capacity xsi:nil='true'></Capacity>
                <Year_of_construction>1794</Year_of_construction>
            </Place_of_interest>
            
            <Place_of_interest Place_of_interest_ID='10' City_City_ID='2'>
                <Name>Roazhon Park</Name>
                <Type>Stadium</Type>
                <City>Rennes</City>
                <Country>France</Country>
                <Geo_location_long>-1.7129</Geo_location_long>
                <Geo_location_lat>48.1075</Geo_location_lat>
                <City_WOEID>619163</City_WOEID>
                <Postcode>35000</Postcode>
                <Capacity>29778</Capacity>
                <Year_of_construction>1912</Year_of_construction>
            </Place_of_interest>
            
            <Place_of_interest Place_of_interest_ID='11' City_City_ID='2'>
                <Name>Le Grill</Name>
                <Type>Restaurant</Type>
                <City>Rennes</City>
                <Country>France</Country>
                <Geo_location_long>-1.6828</Geo_location_long>
                <Geo_location_lat>48.1085</Geo_location_lat>
                <City_WOEID>619163</City_WOEID>
                <Postcode>35000</Postcode>
